language: php
dist: trusty

matrix:
    include:
        - php: 7.1
          env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.*
        - php: 7.2
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
        - php: 7.2
          env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.*
        - php: 7.3
          env: ILLUMINATE_VERSION=7.* TESTBENCH_VERSION=5.*
        - php: 7.3
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
        - php: 7.3
          env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.*
        - php: 7.4
          env: ILLUMINATE_VERSION=7.* TESTBENCH_VERSION=5.*
        - php: 7.4
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*
        - php: 7.4
          env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
        - php: 7.4
          env: ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
        - php: 7.4
          env: ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.*

before_script:

before_install:
    - travis_retry composer self-update
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --dev
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit
